# Generated by Django 5.1 on 2024-10-19 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='apartment',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='квартира'),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='user',
            name='displayname',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Отображаемое имя'),
        ),
        migrations.AddField(
            model_name='user',
            name='floor',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Этаж'),
        ),
        migrations.AddField(
            model_name='user',
            name='house',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Дом'),
        ),
        migrations.AddField(
            model_name='user',
            name='street',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Улица'),
        ),
    ]
