# Generated by Django 5.1 on 2024-10-19 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_user_apartment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='apartment',
            field=models.CharField(default='Unknown', max_length=10, verbose_name='квартира'),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(default='Unknown', max_length=100, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='user',
            name='displayname',
            field=models.CharField(default='Unknown', max_length=255, verbose_name='Отображаемое имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='floor',
            field=models.CharField(default='Unknown', max_length=10, verbose_name='Этаж'),
        ),
        migrations.AlterField(
            model_name='user',
            name='house',
            field=models.CharField(default='Unknown', max_length=10, verbose_name='Дом'),
        ),
        migrations.AlterField(
            model_name='user',
            name='street',
            field=models.CharField(default='Unknown', max_length=100, verbose_name='Улица'),
        ),
    ]
