# Generated by Django 5.1 on 2024-09-20 08:48

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='название')),
            ],
            options={
                'verbose_name': 'бренд',
                'verbose_name_plural': 'бренды',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True, verbose_name='название')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='цвет')),
                ('image', models.ImageField(upload_to='images/', verbose_name='color')),
            ],
            options={
                'verbose_name': 'Цвет',
                'verbose_name_plural': 'Цветы',
            },
        ),
        migrations.CreateModel(
            name='Flag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Флаг')),
                ('image', models.ImageField(upload_to='images/', verbose_name='флаг')),
            ],
            options={
                'verbose_name': 'Флаг',
                'verbose_name_plural': 'Флаги',
            },
        ),
        migrations.CreateModel(
            name='FrameMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='название')),
            ],
            options={
                'verbose_name': 'Материал рам',
                'verbose_name_plural': 'Материал рамы',
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='название')),
            ],
            options={
                'verbose_name': 'размер',
                'verbose_name_plural': 'размеры',
            },
        ),
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата добавление')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('description', models.CharField(help_text='Просто описание', max_length=400, verbose_name='описание')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='цена')),
                ('is_published', models.BooleanField(default=True, verbose_name='публичность')),
                ('receive_type', models.CharField(choices=[('in_stock', 'в наличии'), ('sold_out', 'распродано')], default='in_stock', max_length=15, verbose_name='условия получение')),
                ('image', models.ImageField(upload_to='images/', verbose_name='выберите велосипед')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('wheel_diameter', models.DecimalField(decimal_places=1, default=0.0, max_digits=3, verbose_name='Диаметр колеса')),
                ('tires', models.CharField(max_length=170, verbose_name='Покрышки')),
                ('frame', models.CharField(max_length=170, verbose_name='рамка')),
                ('seatpost', models.CharField(max_length=170, verbose_name='Подседельный Штырь')),
                ('saddle', models.CharField(max_length=170, verbose_name='седло')),
                ('fork', models.CharField(max_length=170, verbose_name='Вилка')),
                ('takeaway', models.CharField(max_length=170, verbose_name='Вынос')),
                ('wheels', models.CharField(max_length=170, verbose_name='Колеса')),
                ('handlebar', models.CharField(max_length=170, verbose_name='руль')),
                ('brake_type', models.CharField(choices=[('disc', 'Disc'), ('hydraulic', 'Hydraulic'), ('mechanical', 'Mechanical')], default='disc', max_length=50)),
                ('brake_system', models.CharField(max_length=170, verbose_name='Тормозная система')),
                ('shifters', models.CharField(max_length=170, verbose_name='Манетки')),
                ('connecting_rod_system', models.CharField(max_length=170, verbose_name='Система шатунов')),
                ('rear_derailleur', models.CharField(max_length=100, verbose_name='Задний переключатель')),
                ('Chain', models.CharField(max_length=50, verbose_name='Цепь')),
                ('num_gears', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('warranty_years', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
                ('brand', models.ForeignKey(help_text='Выберите бренд', on_delete=django.db.models.deletion.PROTECT, to='bike.brand', verbose_name='бренд')),
                ('category', models.ForeignKey(help_text='Выберите категорию', on_delete=django.db.models.deletion.PROTECT, to='bike.category', verbose_name='категория')),
                ('color', models.ForeignKey(help_text='Выберите цвет', on_delete=django.db.models.deletion.PROTECT, to='bike.color', verbose_name='Цвет')),
                ('flag', models.ForeignKey(help_text='Выберите флаг', on_delete=django.db.models.deletion.PROTECT, to='bike.flag', verbose_name='флаг')),
                ('Frame_material', models.ForeignKey(help_text='Выберите Материал рамы', on_delete=django.db.models.deletion.PROTECT, to='bike.framematerial', verbose_name='Материал рам')),
                ('size', models.ForeignKey(help_text='Выберите размер', on_delete=django.db.models.deletion.PROTECT, to='bike.size', verbose_name='размер')),
            ],
            options={
                'verbose_name': 'велосипед',
                'verbose_name_plural': 'велосипеды',
            },
        ),
    ]
