# Generated by Django 5.1 on 2024-10-09 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bike',
            old_name='Frame_material',
            new_name='frame_material',
        ),
        migrations.AlterField(
            model_name='bike',
            name='receive_type',
            field=models.CharField(choices=[('in_stock', 'в наличии')], default='in_stock', max_length=15, verbose_name='условия получение'),
        ),
    ]
