# Generated by Django 5.1 on 2024-09-24 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bike',
            old_name='Frame_material',
            new_name='frame_material',
        ),
    ]
