# Generated by Django 5.1 on 2024-10-20 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0005_alter_order_order_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
    ]
